export function jsonResponse(body: unknown, init: ResponseInit = {}) {
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { 'content-type': 'application/json', ...(init.headers ?? {}) },
    ...init,
  })
}

export const settingsDiagnosticsFixture = {
  generatedAt: '2026-05-09T00:00:00Z',
  service: {
    name: 'Oratorio',
    mode: 'test',
    workspaceMode: 'single',
  },
  capabilities: {
    serverConfigurationWrites: true,
  },
  gitHub: {
    available: true,
    enabled: true,
    authentication: 'app',
    writesEnabled: true,
    writeConfigured: true,
    webhookSecretConfigured: true,
    endpoint: 'https://api.github.com',
    repositories: ['example-owner/oratorio'],
    lastSyncAt: '2026-05-09T00:00:00Z',
  },
  gitLab: {
    available: true,
    enabled: true,
    authentication: 'accessToken',
    writesEnabled: true,
    writeConfigured: true,
    webhookSecretConfigured: true,
    webhookSigningTokenConfigured: false,
    webhookVerificationMode: 'secretToken',
    endpoint: 'https://gitlab.example.test',
    apiBaseUrl: 'https://gitlab.example.test/api/v4',
    projects: ['group/subgroup/project'],
    lastSyncAt: '2026-05-09T00:00:00Z',
    recentSyncFailures: [],
    recentSourceWriteFailures: [],
  },
  dotCraft: {
    available: true,
    configured: true,
    connected: true,
    health: 'connected',
    endpoint: 'ws://127.0.0.1:5089',
    endpointSource: 'test',
    workspacePath: 'C:/example/workspaces/oratorio',
    autoStart: true,
    hubDiscoveryEnabled: false,
    approvalPolicy: 'interrupt',
    runTimeoutSeconds: 1800,
    managedWorktreesEnabled: true,
    worktreeRoot: '.craft/worktrees',
    worktreeRootPolicy: 'workspace',
    worktreeBranchPrefix: 'oratorio/',
    globalMaxActiveRuns: 1,
    maxActiveRunsPerRepository: 1,
    maxActiveRunsPerSource: 1,
    maxRunAttempts: 2,
    retryBackoffSeconds: 10,
    maxRetryBackoffSeconds: 60,
    stallTimeoutSeconds: 300,
    succeededWorktreeRetentionHours: 24,
    failedWorktreeRetentionHours: 72,
    worktreeCleanupEnabled: true,
    worktreeCleanupIntervalSeconds: 300,
  },
  redaction: {
    secretsRedacted: true,
    redactedFields: ['token'],
    urlPartsRemoved: ['query'],
  },
}

export const serverConfigurationFixture = {
  generatedAt: '2026-05-09T00:00:00Z',
  writable: true,
  disabledReason: null,
  revision: 'revision-1234567890',
  overlayPath: '.craft/oratorio.json',
  configuration: {
    gitHub: {
      endpoint: 'https://api.github.com',
      appId: '123',
      installationProfiles: [
        { instance: 'github.com', owner: 'example-owner', installationId: '456', source: 'manual' },
      ],
      repositories: ['example-owner/oratorio'],
      writesEnabled: true,
      secrets: {
        token: { configured: true, mode: 'unchanged', value: null },
        privateKey: { configured: true, mode: 'unchanged', value: null },
        privateKeyPath: { configured: false, mode: 'unchanged', value: null },
        webhookSecret: { configured: true, mode: 'unchanged', value: null },
      },
    },
    gitLab: {
      enabled: true,
      writesEnabled: true,
      endpoint: 'https://gitlab.example.test',
      apiBaseUrl: 'https://gitlab.example.test/api/v4',
      projects: ['group/subgroup/project'],
      projectProfiles: [
        {
          instance: 'gitlab.example.test',
          projectPath: 'group/subgroup/project',
          tokenKind: 'accessToken',
          secrets: {
            token: { configured: true, mode: 'unchanged', value: null },
            webhookSecret: { configured: true, mode: 'unchanged', value: null },
            webhookSigningToken: { configured: false, mode: 'unchanged', value: null },
          },
        },
      ],
      allowLocalDevelopmentUnsafeWebhooks: false,
    },
    dotCraft: {
      repositoryWorkspaces: {
        'example-owner/oratorio': 'C:/example/workspaces/oratorio',
        'gitlab:gitlab.example.test/group/subgroup/project': 'C:/example/workspaces/oratorio',
      },
      appServerUrl: 'ws://127.0.0.1:5089',
      hubDiscoveryEnabled: false,
      hubLockPath: '',
      approvalPolicy: 'interrupt',
      runTimeoutSeconds: 1800,
    },
    runtime: {
      managedWorktreesEnabled: true,
      worktreeRoot: '.craft/worktrees',
      worktreeBranchPrefix: 'oratorio/',
      globalMaxActiveRuns: 1,
      maxActiveRunsPerRepository: 1,
      maxActiveRunsPerSource: 1,
      maxRunAttempts: 2,
      retryBackoffSeconds: 10,
      maxRetryBackoffSeconds: 60,
      stallTimeoutSeconds: 300,
      succeededWorktreeRetentionHours: 24,
      failedWorktreeRetentionHours: 72,
      worktreeCleanupEnabled: true,
      worktreeCleanupIntervalSeconds: 300,
    },
    automation: {
      autoDispatchEnabled: false,
      autoDispatchAllowLabels: [],
      autoDispatchBlockLabels: [],
      deliveryPolicy: 'manualDelivery',
      maxImplementationTurns: 4,
      autoReviewRepositories: [],
      autoReviewPublishEnabled: false,
      autoReviewPublishRepositories: [],
      autoFollowUpEnabled: false,
      autoFollowUpRepositories: [],
      maxFollowUpRounds: 5,
    },
  },
  impactWarnings: [],
  recentChanges: [],
  restartRequired: false,
  restartSignature: null,
}

export const workspaceInventoryFixture = {
  generatedAt: '2026-05-09T00:00:00Z',
  summary: {
    total: 1,
    connected: 1,
    hubManaged: 0,
    defaultPath: '',
  },
  workspaces: [
    {
      path: 'C:/example/workspaces/oratorio',
      label: 'oratorio',
      isDefault: false,
      repositories: ['example-owner/oratorio', 'gitlab:gitlab.example.test/group/subgroup/project'],
      configured: true,
      connected: true,
      health: 'connected',
      endpoint: 'ws://127.0.0.1:5089',
      endpointSource: 'test',
      hubManaged: false,
      reason: 'ok',
      message: 'Connected.',
    },
  ],
}
